[package]
name = "rust-llm-rag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qdrant-client = "1.8.0"
tokio = { version = "1", features = ["full"] }
config = "0.14.0"